{ pkgs, ... }:
with pkgs;
let
  todo = "todo";
  cantfind = "cantfind";
in
{
  "0trace" = todo;
  ace-voip = todo;
  aesfix = todo; #TODO pkgs.aesfix from 22.05
  aeskeyfind = todo; #TODO pkgs.aeskeyfind from 22.05
  afflib-tools = pkgs.afflib;
  "afl++" = pkgs.aflplusplus;
  aircrack-ng = pkgs.aircrack-ng;
  apache2 = pkgs.apacheHttpd;
  apache-users = todo;
  apktool = pkgs.apktool;
  arachni = todo;
  armitage = todo;
  "arping | iputils-arping" = pkgs.arping;
  asleap = todo; #TODO pkgs.asleap from 22.11
  autopsy = todo;
  backdoor-factory = todo;
  bed = todo; # a fork of BED is available in Nixpkgs 20.09 as pkgs.doona
  beef-xss = nur.repos.makefu.beef;
  bettercap = pkgs.bettercap;
  binwalk = pkgs.python3Packages.binwalk-full;
  bluelog = todo;
  blueranger = todo;
  bluesnarfer = todo;
  bluez = pkgs.bluez;
  bluez-hcidump = todo;
  braa = todo;
  btscanner = todo;
  bulk-extractor = todo;
  bully = pkgs.bully;
  burpsuite = pkgs.burpsuite;
  bytecode-viewer = todo;
  cabextract = pkgs.cabextract;
  cadaver = pkgs.cadaver;
  ccrypt = pkgs.ccrypt;
  cdpsnarf = todo;
  cewl = todo; #TODO pkgs.cewl from 21.11
  chirp = pkgs.chirp;
  chkrootkit = pkgs.chkrootkit;
  chntpw = pkgs.chntpw;
  cisco-auditing-tool = todo;
  cisco-global-exploiter = todo;
  cisco-ocs = todo;
  cisco-torch = todo;
  clang = pkgs.clang;
  cmospwd = todo;
  commix = todo; #TODO pkgs.commix from 22.11
  cookie-cadger = todo;
  copy-router-config = todo;
  cowpatty = pkgs.cowpatty;
  crackle = todo; #TODO pkgs.crackle from 21.11
  crackmapexec = todo; #TODO pkgs.crackmapexec from 22.11
  creddump7 = todo;
  crunch = pkgs.crunch;
  cutecom = pkgs.cutecom;
  cutycapt = todo;
  cymothoa = todo;
  darkstat = pkgs.darkstat;
  davtest = todo; #TODO pkgs.davtest from 22.11
  dbd = todo;
  dc3dd = todo;
  dcfldd = pkgs.dcfldd;
  ddrescue = pkgs.ddrescue;
  default-mysql-server = todo;
  dex2jar = nur.repos.makefu.dex2jar;
  dhcpig = todo;
  dirb = pkgs.dirb;
  dirbuster = todo;
  dmitry = todo;
  dns2tcp = todo;
  dnschef = todo; #TODO pkgs.dnschef from 21.11
  dnsenum = pkgs.dnsenum;
  dnsmap = todo;
  dnsrecon = pkgs.dnsrecon;
  dnstracer = pkgs.dnstracer;
  dnswalk = todo;
  dotdotpwn = todo;
  dradis = todo;
  driftnet = pkgs.driftnet;
  dsniff = pkgs.dsniff;
  dumpzilla = todo;
  eapmd5pass = todo;
  edb-debugger = nur.repos.bb010g.pkgs.edb-debugger;
  enum4linux = pkgs.enum4linux;
  enumiax = todo;
  "ettercap-graphical | ettercap-text-only" = pkgs.ettercap;
  ewf-tools = todo;
  exe2hexbat = todo;
  exifprobe = todo; #TODO pkgs.exifprobe from 21.05
  exiv2 = pkgs.exiv2;
  exploitdb = nur.repos.jjjollyjim.exploitdb; #TODO pkgs.exploitdb from 22.05
  ext3grep = todo;
  ext4magic = pkgs.ext4magic;
  extundelete = pkgs.extundelete;
  eyewitness = todo;
  faraday = todo; #TODO pkgs.faraday-cli from 21.11
  fcrackzip = pkgs.fcrackzip;
  fern-wifi-cracker = todo;
  fierce = pkgs.fierce;
  fiked = todo;
  firewalk = todo;
  firmware-mod-kit = todo;
  flashrom = pkgs.flashrom;
  flasm = todo; #TODO pkgs.flasm from 21.05
  foremost = pkgs.foremost;
  forensic-artifacts = todo;
  forensics-colorize = todo;
  fping = pkgs.fping;
  fragrouter = todo;
  freeradius-wpe = pkgs.freeradius;
  freerdp2-x11 = todo;
  ftester = todo;
  galleta = todo;
  gdb = pkgs.gdb;
  gnuradio = pkgs.gnuradio;
  gpart = pkgs.gpart;
  gparted = pkgs.gparted;
  gpp-decrypt = todo;
  gqrx-sdr = pkgs.gqrx;
  gr-air-modes = todo;
  gr-iqbal = todo;
  grokevt = todo;
  gr-osmosdr = pkgs.gr-osmosdr;
  guymager = todo;
  hackrf = pkgs.hackrf;
  hamster-sidejack = todo;
  hashcat = pkgs.hashcat;
  hashcat-utils = pkgs.hashcat-utils;
  hashdeep = pkgs.hashdeep;
  hashid = todo;
  hash-identifier = todo; #TODO pkgs.hash-identifier from 21.11
  heartleech = todo;
  hexinject = todo;
  hostapd-wpe = todo; #TODO pkgs.hostapd is a different project (the one in Kali seems to be part of aircrack-ng?)
  hping3 = pkgs.hping;
  httprint = todo;
  httrack = pkgs.httrack;
  hydra = pkgs.thc-hydra;
  hydra-gtk = pkgs.thc-hydra.override (_: { withGUI = true; });
  hyperion = todo; #TODO pkgs.hyperion-ng is a different project
  iaxflood = todo;
  ike-scan = todo; #TODO pkgs.ike-scan from 21.05
  inetsim = todo;
  inspectrum = pkgs.inspectrum;
  intrace = todo;
  inviteflood = todo;
  iodine = pkgs.iodine;
  irpas = todo;
  isr-evilgrade = todo;
  iw = pkgs.iw;
  jadx = pkgs.jadx;
  javasnoop = todo;
  jboss-autopwn = todo;
  jd-gui = pkgs.jd-gui;
  john = pkgs.john;
  johnny = todo;
  joomscan = todo;
  jsql-injection = todo;
  kalibrate-rtl = pkgs.kalibrate-rtl;
  killerbee = todo;
  kismet = pkgs.kismet;
  laudanum = todo;
  lbd = todo;
  legion = todo;
  libfindrtp = todo;
  libfreefare-bin = pkgs.libfreefare;
  libhivex-bin = pkgs.hivex;
  libnfc-bin = pkgs.libnfc;
  lime-forensics = todo;
  lvm2 = pkgs.lvm2;
  lynis = pkgs.lynis;
  macchanger = pkgs.macchanger;
  mac-robber = todo;
  magicrescue = todo;
  maltego = todo;
  maskprocessor = todo;
  masscan = pkgs.masscan;
  md5deep = todo;
  mdbtools = pkgs.mdbtools;
  mdk3 = todo;
  mdk4 = todo; #TODO pkgs.mdk4 from 21.11
  medusa = pkgs.medusa;
  memdump = todo;
  metacam = todo;
  metagoofil = todo;
  metasploit-framework = pkgs.msf;
  mfcuk = pkgs.mfcuk;
  mfoc = pkgs.mfoc;
  mfterm = todo;
  mimikatz = todo;
  minicom = pkgs.minicom;
  miredo = pkgs.miredo;
  missidentify = todo;
  mitmproxy = pkgs.mitmproxy;
  msfpc = todo; #TODO pkgs.msfpc from 22.11
  multimon-ng = pkgs.multimon-ng;
  myrescue = todo;
  nasm = pkgs.nasm;
  nasty = pkgs.nasty;
  nbtscan = todo; #TODO pkgs.nbtscanner is a different project, though it seems to be for the same thing
  ncat = pkgs.ncat;
  ncat-w32 = todo;
  ncrack = todo; #TODO pkgs.ncrack from 21.05
  netdiscover = todo; #TODO pkgs.netdiscover from 21.11
  netmask = pkgs.netmask;
  netsniff-ng = pkgs.netsniff-ng;
  nikto = todo; #TODO pkgs.nikto from 21.05
  nishang = todo;
  nmap = pkgs.nmap;
  oclgausscrack = todo;
  ohrwurm = todo;
  ollydbg = todo;
  onesixtyone = pkgs.onesixtyone;
  openocd = pkgs.openocd;
  openvas = todo;
  ophcrack = todo;
  ophcrack-cli = todo;
  oscanner = todo;
  outguess = todo;
  owasp-mantra-ff = todo;
  p0f = pkgs.p0f;
  p7zip-full = pkgs.p7zip;
  pack = todo;
  padbuster = todo; #TODO pkgs.padbuster from 22.11
  paros = todo;
  parted = pkgs.parted;
  pasco = todo;
  passing-the-hash = todo;
  patator = pkgs.python3Packages.patator;
  pdfcrack = pkgs.pdfcrack;
  pdfid = todo;
  pdf-parser = pkgs.pdf-parser;
  pev = pkgs.pev;
  php = pkgs.php;
  php-mysql = phpExtensions.mysqlnd;
  pipal = todo;
  pixiewps = pkgs.pixiewps;
  plaso = todo;
  plecost = todo; #TODO pkgs.plecost from 22.11
  polenum = todo;
  powercat = todo;
  powersploit = todo;
  protos-sip = todo;
  proxychains = pkgs.proxychains;
  proxytunnel = pkgs.proxytunnel;
  pst-utils = todo;
  ptunnel = nur.repos.sikmir.ptunnel;
  pwnat = pkgs.pwnat;
  python3-capstone = pkgs.python3Packages.capstone;
  python3-dfdatetime = cantfind;
  python3-dfvfs = cantfind;
  python3-dfwinreg = cantfind;
  python3-distorm3 = pkgs.python3Packages.distorm3;
  qemu = pkgs.qemu;
  qsslcaudit = todo;
  radare2 = pkgs.radare2;
  radare2-cutter = pkgs.radare2-cutter;
  rainbowcrack = todo;
  rarcrack = pkgs.rarcrack;
  rcracki-mt = todo;
  reaver = pkgs.reaverwps;
  rebind = todo;
  recon-ng = todo;
  recordmydesktop = cantfind;
  recoverdm = todo;
  recoverjpeg = pkgs.recoverjpeg;
  redfang = todo; #TODO pkgs.redfang from 21.11
  redsocks = pkgs.redsocks;
  reglookup = todo;
  regripper = todo;
  rekall-core = todo;
  rephrase = todo;
  responder = cantfind;
  rfcat = todo;
  rfdump = todo;
  rfkill = pkgs.rfkill;
  rifiuti = todo;
  rifiuti2 = todo;
  rkhunter = todo;
  rsakeyfind = todo;
  rsmangler = todo;
  rtlsdr-scanner = todo;
  rtpbreak = todo;
  rtpflood = todo;
  rtpinsertsound = todo;
  rtpmixsound = todo;
  safecopy = pkgs.safecopy;
  sakis3g = todo;
  samdump2 = todo;
  sandsifter = todo;
  sbd = todo;
  scalpel = todo;
  scrounge-ntfs = todo;
  sctpscan = todo;
  seclists = todo;
  secure-socket-funneling-windows-binaries = todo;
  set = todo;
  sfuzz = todo;
  shellnoob = todo; #TODO pkgs.shellnoob from 22.11
  shellter = todo;
  sidguesser = todo;
  siege = pkgs.siege;
  siparmyknife = todo;
  sipcrack = todo;
  sipp = pkgs.sipp;
  sipsak = pkgs.sipsak;
  sipvicious = todo; #TODO pkgs.sipvicious from 21.05
  skipfish = todo;
  sleuthkit = pkgs.sleuthkit;
  slowhttptest = todo; #TODO pkgs.slowhttptest from 21.05
  smali = todo;
  smbmap = todo;
  smtp-user-enum = todo;
  sniffjoke = todo;
  snmpcheck = pkgs.net-snmp;
  spectools = todo;
  spike = pkgs.spike;
  spooftooph = todo;
  sqldict = todo;
  sqlitebrowser = pkgs.sqlitebrowser;
  sqlmap = pkgs.sqlmap;
  sqlninja = todo;
  sqlsus = todo;
  ssdeep = pkgs.ssdeep;
  ssldump = pkgs.ssldump;
  sslh = pkgs.sslh;
  sslscan = pkgs.sslscan;
  sslsniff = todo;
  sslsplit = pkgs.sslsplit;
  sslyze = todo;
  statsprocessor = todo;
  steghide = pkgs.steghide;
  stegsnow = todo;
  stunnel4 = todo;
  sucrack = todo;
  swaks = pkgs.swaks;
  t50 = todo;
  tcpdump = pkgs.tcpdump;
  tcpflow = pkgs.tcpflow;
  tcpick = todo;
  tcpreplay = pkgs.tcpreplay;
  termineter = todo;
  tftpd32 = todo;
  thc-ipv6 = todo; #TODO pkgs.thc-ipv6 from 21.05
  thc-pptp-bruter = todo;
  thc-ssl-dos = todo;
  theharvester = pkgs.theharvester;
  tlssled = todo;
  tnscmd10g = todo;
  truecrack = todo; #TODO pkgs.truecrack from 21.11 (also truecrack-cuda but that's marked broken)
  twofi = todo;
  ubertooth = todo; #TODO pkgs.ubertooth from 21.05
  udptunnel = pkgs.udptunnel;
  uhd-host = pkgs.uhd;
  uhd-images = todo;
  undbx = todo;
  unhide = todo;
  unicornscan = todo;
  uniscan = todo;
  unix-privesc-check = todo;
  "unrar | unar" = pkgs.unrar;
  upx-ucl = todo;
  urlcrazy = todo;
  veil = todo;
  vinetto = todo;
  voiphopper = todo;
  volatility = pkgs.volatility;
  wafw00f = todo; #TODO pkgs.wafw00f from 21.05
  wapiti = todo; #TODO pkgs.wapiti from 21.05
  watobo = todo;
  wce = todo;
  webacoo = todo;
  webscarab = todo;
  webshells = todo;
  weevely = todo;
  wfuzz = pkgs.wfuzz;
  whatweb = todo; #TODO pkgs.whatweb from 22.05
  wifi-honey = todo;
  wifite = pkgs.wifite2;
  windows-binaries = todo;
  windows-privesc-check = todo;
  winregfs = todo;
  wireshark = pkgs.wireshark;
  wordlists = todo;
  wpscan = pkgs.wpscan;
  xmount = todo;
  xplico = todo;
  xprobe = todo;
  xsser = todo; #TODO pkgs.xsser from 22.11
  yara = pkgs.yara;
  yersinia = todo; #TODO pkgs.yersinia from 22.05
  zaproxy = pkgs.zap;
}
